new copy button
IBM/libras-ui pull request #24
Opened 2020-08-31 20:10 UTC by adamalston

Fixes #12 

### Overview 
- [x] Add new copy button with `scss` so that the button scales correctly
 - Unsure if I should delete the old button, the issue didn't specify
- [x] Make copy button appear onClick
- [x] Use React ref to copy text from textarea to clipboard
- [x] Show confirmation that text was copied

![0](https://user-images.githubusercontent.com/18297826/91763552-bfe6ec00-eba3-11ea-9295-d332b0704958.png)
![1](https://user-images.githubusercontent.com/18297826/91763571-c5443680-eba3-11ea-9d28-cf4161decb21.png)
![2](https://user-images.githubusercontent.com/18297826/91763582-c9705400-eba3-11ea-9783-05f722a67c7b.png)

2020-09-03 12:06 UTC, filipecorrea commented
Hi @adamalston. Thanks for your contribution. It's not clear to me why you did not follow the layout and added a new button on this screen. Do you think there is a problem with the proposed layout?

2020-09-03 17:42 UTC, adamalston commented
The issue said:

> Add a ghost button in the Review box so that the user can copy what has been translated to the clipboard.

I followed this and put the button in the review box. Also, the issue didn't specify whether the old button should be removed. Any feedback or edits were expected since the instructions were a little unclear.

2020-09-03 18:31 UTC, filipecorrea commented
You're right, the issue wasn't clear enough. Sorry about that.

I just updated the issue description to the appropriate behavior that's being expected. I hope you don't mind updating your code to reflect that.

2020-09-04 07:06 UTC, adamalston commented
Question: should the button be inside of the textarea (like #12 said before), or should it be outside of the textarea as it is in the following image? My code has it inside but I could easily move it outside.
![0](https://user-images.githubusercontent.com/33586050/90770693-8ae7b900-e2c8-11ea-93ae-d64f3d177fa9.png)

2020-09-07 21:10 UTC, camilasb commented
Can I see how it will be at the end to check out the design?

2020-09-08 20:02 UTC, filipecorrea requested changes
It's working as expected, but I'm missing unit tests. I think it would be good to check if (and when) the button is rendered and validate what's happening when it's clicked.

2020-09-08 20:20 UTC, filipecorrea commented
@camilasb Adam updated the screenshot in the pull request description, but I'm sending another one anyway:

![Screen Shot 2020-09-08 at 17 02 58](https://user-images.githubusercontent.com/1496656/92523857-7461bd00-f1f7-11ea-8427-0edcf15d6a0f.png)

While testing this one, I found two SCSS problems unrelated to this issue: #25 and #26.

2020-09-08 23:48 UTC, adamalston commented
I do not have much experience testing buttons and onClick events so any assistance there would be appreciated. Further, if someone wants to contribute the tests themselves, I would fine with that.

I can confirm #25 on my end as well (macOS, Firefox 80.0.1). My screenshot appears different because I am using a dark mode extension which automatically makes the page darker and increases contrast between text and background.

2020-09-09 12:57 UTC, filipecorrea commented
@adamalston [React Test Utilities](https://reactjs.org/docs/test-utils.html) is a good place to start and [this example](https://reactjs.org/docs/test-utils.html#act) has all that you need to create a `src/content/UserPage/UserPage.test.js`.

Please give a try and I can continue helping you using code reviews.

2020-09-09 22:50 UTC, camilasb commented
@filipecorrea if there's an env for testing, let me know :D i can take a look at that as well

2020-09-10 09:45 UTC, filipecorrea commented
@camilasb We don't have this code deployed yet. You'll need to run it locally at this moment.

2020-09-10 11:42 UTC, camilasb commented
> @camilasb We don't have this code deployed yet. You'll need to run it locally at this moment.

i see! tks :D

2025-05-21 05:00 UTC, closed without merging